language: php

services:
  - redis-server

git:
  submodules: false

php:
  - 7
  - 5.6
  - 5.5
  - 5.4

before_script:
  - composer install

script: php ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-text